### ISSUE TITLE
Can't compile with Ubuntu 20.10

### ISSUE THREAD

**Issue by rolandbreedveld** [its-izhar/rtl88x2bu-driver#15]
Compiling with Ubuntu 20.10 gives these errors:

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.8.0-26-generic/build M=/usr/src/rtl88x2bu-driver  modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-26-generic'
  CC [M]  /usr/src/rtl88x2bu-driver/core/rtw_cmd.o
In file included from /usr/src/rtl88x2bu-driver/include/drv_types.h:78,
                 from /usr/src/rtl88x2bu-driver/core/rtw_cmd.c:17:
/usr/src/rtl88x2bu-driver/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from ./include/linux/filter.h:23,
                 from ./include/net/sock.h:59,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:88,
                 from ./include/net/addrconf.h:50,
                 from /usr/src/rtl88x2bu-driver/include/osdep_service_linux.h:48,
                 from /usr/src/rtl88x2bu-driver/include/osdep_service.h:50,
                 from /usr/src/rtl88x2bu-driver/include/drv_types.h:27,
                 from /usr/src/rtl88x2bu-driver/core/rtw_cmd.c:17:
./include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:290: /usr/src/rtl88x2bu-driver/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1780: /usr/src/rtl88x2bu-driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-26-generic'
make: *** [Makefile:1986: modules] Error 2
