### ISSUE TITLE
fails to compile with kernel 4.19+

### ISSUE THREAD

**Issue by JonCStout** [its-izhar/rtl88x2bu-driver#3]
Here's the complete error output followed by a web link to another bug report, with an included fix, that might be relevant.

~/rtl88x2bu-driver/os_dep/linux/os_intfs.c:1429:22: error: initialization of ‘u16 (*)(struct net_device *, struct sk_buff *, struct net_device *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} from incompatible pointer type ‘u16 (*)(struct net_device *, struct sk_buff *, void *, u16 (*)(struct net_device *, struct sk_buff *, struct net_device *))’ {aka ‘short unsigned int (*)(struct net_device *, struct sk_buff *, void *, short unsigned int (*)(struct net_device *, struct sk_buff *, struct net_device *))’} [-Werror=incompatible-pointer-types]
  .ndo_select_queue = rtw_select_queue,

"The interface of ndo_select_queue callback has changed.":
https://github.com/smlinux/rtl8723de/issues/27

**Comment by its-izhar** [comment]
Fixed it in following commits:
[[4.19] Fixed redefinition of IEEE80211_MAX_AMPDU_BUF Macro](https://github.com/its-izhar/rtl88x2bu-driver/commit/0d2ad21fa6346e46c5d623adf4def0603c7e257f)
[[4.19] Fixed function definition of 'rtw_select_queue'](https://github.com/its-izhar/rtl88x2bu-driver/commit/8fc5f40ff567522536ad85c2cfef13dbc9b2581e)

Closing it.
--
IS
